### ISSUE TITLE
[BUG] Clique duplo em "Começar" faz relógio não parar.

### ISSUE THREAD

**Issue by mAngelo-dev** [GPMLAD/Cronometro-JS#1]
Quando você clica 2x em começar, o relógio não para mesmo com o botão parar, somente resetando a página você consegue voltar ele pro estado original ou apertando em reset, mas o cronômetro continua rodando.

**Comment by GPMLAD** [comment]
Nossa, eu não fazia ideia! Obrigado por ter achado esse bug. Esse final de semana vou ter um tempinho e vou concertar :+1:

**Comment by mAngelo-dev** [comment]
Parabéns pelo projeto! Tenho certeza que vai ficar 100% após a correção do bug!

**Comment by GPMLAD** [comment]
Adicionei uma classe secundário "off" para regular a utilização do botão começar. Creio que o problema tenha sido resolvido.
